### PR TITLE
Added SD card and GPS breakout board symbols

### PR DESCRIPTION
**Pull request by nikhilantony28**
Connected the micro SD Card and the GPS breakout board to Ardiuno Nano. Not sure on sending the bus signals from 3.3V to 5V voltage levels so copied M4 Avionics using a pull up resistor. Found some a website with information on this here: https://next-hack.com/index.php/2020/02/15/how-to-interface-a-3-3v-output-to-a-5v-input/

### CODE REVIEW

**Review by henryefranks — CHANGES_REQUESTED** [review]
I think the way to handle the SD card is to use a level shifter like on commercial breakout boards. We could probably just copy [this schematic](https://learn.adafruit.com/adafruit-micro-sd-breakout-board-card-tutorial/download) because from what I gather they're fairly reliable.

Otherwise, make sure we're only using parts from the cusf-kicad library for portability. Everything we need *should* be in there but let me know if we need to add an ic or two. Using just the cusf library makes it really easy for anyone to see the same thing if any of the default libraries change, or if they're not installed.

Apart from those two things, great work! Thanks for getting this sorted, hopefully we can move onto testing firmware and getting a PCB design sent off soon for a good v1 to stick on HAB launches, then work out the kinks and maybe add telemetry for a second revision.

**Comment by DanielFearn** [comment]
I might be wrong but it looks like Rx on the arduino is connected to Rx on the gps, and Tx to Tx, shouldn't they be flipped?

**Comment by henryefranks** [comment]
Yeah you're right. Good spot!

**Comment by henryefranks** [comment]
Also @nikhilantony28 I've noticed that you've hardcoded the path to cusf-kicad in the sym-lib-table, make sure to submodule it like in [Strix](https://github.com/cuspaceflight/strix).

**Pull request merged**
